config/routes.rb
Rails.application.routes.draw do
  
  resources :generators,
            path: "templates" do
    member do
      post :sort_snippets
    end
  end
  
  resources :snippets
  
  devise_for :users, controllers: { sessions:      'users/sessions',
                                    registrations: 'users/registrations',
                                    passwords:     'users/passwords' }
  
  get 'resources' => 'pages#resources'
  get ':id'       => 'pages#profile', as: :user_profile

  root "pages#home"
  

end

app/models/generator.rb
class Generator < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders, :history]

  attr_accessor :email
  
  belongs_to :author, class_name: "User"

  has_many :generator_snippets, -> {order(position: :asc)}
  has_many :snippets, through: :generator_snippets

  validates_presence_of :name

  validates_uniqueness_of :name

  before_save :ensure_privacy_token

  def ensure_privacy_token
    unless self.privacy_token.present?
      self.privacy_token = SecureRandom.hex(15)
    end
  end
end

app/controllers/generators_controller.rb
class GeneratorsController < ApplicationController
  before_action :authenticate_user!, except: [:new, :show]
  before_action :set_generator, only: [:show, :edit, :update, :destroy, :sort_snippets]

  def sort_snippets
    puts "#{params}"
    params[:snippet].each_with_index do |id, index|
      generator_snippet = @generator.generator_snippets.find_by(snippet_id: id)
      generator_snippet.update_attribute(:position, (index + 1)) if generator_snippet
    end
    
    render nothing: true
  end

  # GET /generators
  # GET /generators.json
  def index
    @personal_generators = current_user.generators.order(is_featured: :desc, name: :asc).all
    @public_generators   = Generator.where.not(author_id: current_user.id).where(is_private: false).order(is_featured: :desc, name: :asc).all
  end

  # GET /generators/1
  # GET /generators/1.json
  def show
    verify_privacy_settings
    @snippets = @generator.snippets
  end

  # GET /generators/new
  def new
    if params[:generator] and params[:generator][:email].present? and current_user.nil?
      ensure_current_user
    end

    if current_user.nil? # This should only trigger on a direct hit to generators/new
      redirect_to new_user_registration_path, notice: "Please signup before continuing."
    else
      @generator = current_user.generators.new

      build_from_dup
      build_from_micro_form
    end

    @accessable_snippets = current_user.accessable_snippets
  end

  # GET /generators/1/edit
  def edit
    @accessable_snippets = current_user.accessable_snippets
  end

  # POST /generators
  # POST /generators.json
  def create
    @generator = current_user.generators.new(generator_params)

    respond_to do |format|
      if @generator.save
        format.html { redirect_to @generator, notice: 'Generator was successfully created.' }
        format.json { render :show, status: :created, location: @generator }
      else
        format.html { render :new }
        format.json { render json: @generator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /generators/1
  # PATCH/PUT /generators/1.json
  def update
    respond_to do |format|
      if @generator.update(generator_params)
        format.html { redirect_to @generator, notice: 'Generator was successfully updated.' }
        format.json { render :show, status: :ok, location: @generator }
      else
        format.html { render :edit }
        format.json { render json: @generator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /generators/1
  # DELETE /generators/1.json
  def destroy
    @generator.destroy
    respond_to do |format|
      format.html { redirect_to generators_url, notice: 'Generator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def build_from_dup
      if params[:dup]
        original_generator     = Generator.find(params[:dup])
        @generator             = original_generator.dup
        @generator.snippet_ids = original_generator.snippet_ids
        @generator.author      = current_user
        
        @generator.name   += " Copy"
      end
    end

    def build_from_micro_form
      if params[:generator]
        if params[:generator][:name].present?
          @generator.name = params[:generator][:name]
        end

        if params[:generator][:snippet_ids].present?
          @generator.snippet_ids = params[:generator][:snippet_ids]
        end
      end
    end

    def verify_privacy_settings
      unless current_user and current_user.can_edit_generator(@generator.id)
        if @generator.is_private
          unless params[:token] and params[:token] == @generator.privacy_token
            redirect_to root_url, notice: "The generator you're trying to access is private."
          end
        end
      end
    end

    def ensure_current_user
      user = User.find_or_create_by(email: params[:generator][:email]) do |u|
        temp_password           = SecureRandom.hex(6)
        u.password              = temp_password
        u.password_confirmation = temp_password
      end

      sign_in user
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_generator
      @generator = Generator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def generator_params
      params.require(:generator).permit(:name,
                                        :is_private,
                                        :author_id,
                                        :is_featured,
                                        snippet_ids: [])
    end
end

app/helpers/generators_helper.rb
module GeneratorsHelper
  def commandline_script(generator_id)
    generator = Generator.find(generator_id)
    url       = generator.is_private ? generator_url(generator, format: :rb, token: generator.privacy_token) : generator_url(generator, format: :rb)
    
    "rails new #{generator.name.parameterize} -m #{url}"
  end
end

app/views/generators/_form.html.haml
= simple_form_for(@generator) do |f|
  = f.error_notification

  .form-inputs
    .form-group
      = f.input :name, input_html: { class: "form-control texteditor" }, label: "Project Name"
      .privacy-option
        = f.input :is_private, label: "Private"

    - if current_user.is_admin
      .form-group 
        = f.input :is_featured

    .form-group
      %label
        Select Snippets
      = f.association :snippets, as: :check_boxes, collection: @accessable_snippets.map { |s| ["<strong>#{s.name}</strong><div class='pull-right small'>#{s.tags.split(",").join(" • ")}</div><br>#{s.description}<br>".html_safe, s.id] },  label: false

  .form-actions.text-center
    = f.button :submit, class: "btn btn-primary btn-lg"

app/views/generators/_form_micro.html.haml
= simple_form_for @generator, url: new_generator_path, method: :get do |f|
  = f.error_notification

  .form-inputs
    - unless current_user
      .form-group
        = f.input :email, input_html: { class: "form-control" }, label: "Your Email"
    .form-group
      = f.input :name, input_html: { class: "form-control texteditor" }, label: "Project Name"
      .privacy-option
        = f.input :is_private, label: "Private"

    .form-group
      %label
        Customize your options
      = f.association :snippets, as: :check_boxes, collection: Snippet.where(is_featured: true, is_private: false).order(:name).map { |s| ["<strong>#{s.name}</strong><div class='pull-right small'>#{s.tags.split(",").join(" • ")}</div><br>#{s.description}<br>".html_safe, s.id] },  label: false

  .form-actions.text-center
    = f.submit "Proceed", class: "btn btn-primary btn-block btn-lg"

app/views/generators/_generator.html.haml
= "# Generator: #{generator.name}"
= "# Author: #{generator.author.email}"
= "# Created via pumptrolley.io, Polar Notion's App Template Tool"
\
= "####################################################"

git :init
git add: "."
git commit: "-a -m 'Initial Commit'"

= "####################################################"

= render generator.snippets

\
= "# Done."
= "# Go Boldy Forward."

app/views/generators/_generator.rb.haml
= "# Generator: #{generator.name}"
= "# Author: #{generator.author.email}"
= "# Created via pumptrolley.io, Polar Notion's App Template Tool"
\
= "####################################################"

git :init
git add: "."
git commit: "-a -m 'Initial Commit'"

= "####################################################"

= render generator.snippets

\
= "# Done."
= "# Go Boldy Forward."

app/views/generators/_table.html.haml
%table.table
  %thead
    %tr
      %th Name
      %th
  %tbody
    - if generators.present?
      - generators.each do |generator|
        %tr
          %td
            = link_to generator.name, generator
            .small.text-muted.hidden-xs
              = generator.snippets.order(name: :asc).map {|s| s.name }.join(" • ")
          %td.text-right.action-column
            = link_to new_generator_url(dup: generator.id), class: "btn text-muted btn-sm" do
              .fa.fa-copy
              Clone
            = link_to generator_url(generator), class: "btn text-muted btn-sm" do
              Show
    - else
      %tr
        %td.text-center{ colspan: 3 }
          %em
            = nil_notice

app/views/generators/edit.html.haml
.container
  %h1
    Edit
    = @generator.name

  = render 'form'

app/views/generators/index.html.haml
%header
  .container
    %h1
      Templates
    %p.text-muted
      App Templates are made up of Snippets and used on new Rails projects.

.container
  / Nav tabs
  .pull-right
    = link_to 'New Template', new_generator_path, class: "btn btn-primary btn-sm"

  %ul.nav.nav-tabs
    %li.active
      %a{"aria-controls" => "personal", "data-toggle" => "tab", :href => "#personal", :role => "tab"} My Templates
    %li
      %a{"aria-controls" => "all", "data-toggle" => "tab", :href => "#all", :role => "tab"} View All

  / Tab panes
  .tab-content.content-wrapper
    #personal.tab-pane.active{:role => "tabpanel"}
      = render "table", generators: @personal_generators, nil_notice: "You haven't created any Generators"
    #all.tab-pane{:role => "tabpanel"}
      = render "table", generators: @public_generators, nil_notice: "There are currently no Public Generators"

    %tfoot
      %tr
        %td{ colspan: 3 }

app/views/generators/new.html.haml
.container
  %h1
    New Template

  = render 'form'

app/views/generators/show.html.haml
.container
  = render "shared/page_title", title: "#{@generator.name} Template", author: @generator.author.email

  - if current_user and current_user.can_edit_generator(@generator.id)
    .pull-right
      = link_to 'Edit Template', edit_generator_path(@generator), class: "btn btn-primary btn-sm"

  %ul.nav.nav-tabs
    %li.active
      %a{"aria-controls" => "install", "data-toggle" => "tab", :href => "#install", :role => "tab"}
        .fa.fa-terminal
        Install
    %li
      %a{"aria-controls" => "source", "data-toggle" => "tab", :href => "#source", :role => "tab"}
        .fa.fa-code
        Source
    %li
      %a{"aria-controls" => "sort", "data-toggle" => "tab", :href => "#sort", :role => "tab"}
        .fa.fa-sort
        Sort

  / Tab panes
  .tab-content.content-wrapper
    #install.tab-pane.fade.in.active{:role => "tabpanel"}
      %p
        To install #{@generator.name} for a new Rails Application, make sure Git and Rails are installed, then run the following script from the command line:
      %pre
        = commandline_script(@generator.id)

    #source.tab-pane.fade.in{:role => "tabpanel"}
      %pre= render @generator

    #sort.tab-pane.fade.in{:role => "tabpanel"}
      %h3
        Snippets

      %ul#sortable.list-unstyled{ "data-update-url" => "#{sort_snippets_generator_url}" }
        - @snippets.each do |snippet|
          = content_tag_for :li, snippet do
            .row.sortable-row 
              .col-xs-12
                %span.handle.text-muted.padded-icon
                  .fa.fa-bars
                = snippet.name
                = snippet.description

  .content-footer-wrapper
    %ul.list-inline
      %li
        = link_to new_generator_url(dup: @generator.id) do
          .fa.fa-copy
          Clone

app/views/generators/show.rb.haml
= render @generator