config/routes.rb
Rails.application.routes.draw do
  
  resources :generators,
            path: "templates" do
    member do
      post :sort_snippets
    end
  end
  
  resources :snippets
  
  devise_for :users, controllers: { sessions:      'users/sessions',
                                    registrations: 'users/registrations',
                                    passwords:     'users/passwords' }
  
  get 'resources' => 'pages#resources'
  get ':id'       => 'pages#profile', as: :user_profile

  root "pages#home"
  

end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders, :history]

  acts_as_list
  
  belongs_to :parent, class_name: "Snippet"
  belongs_to :author, class_name: "User"
  
  has_many :generator_snippets
  has_many :generators, through: :generator_snippets

  validates_presence_of :name,
                        :description,
                        :documentation_url,
                        :install_content,
                        :tags

  before_save :ensure_privacy_token

  def ensure_privacy_token
    unless self.privacy_token.present?
      self.privacy_token = SecureRandom.hex(15)
    end
  end
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_snippet, only: [:show, :edit, :update, :destroy]

  # GET /snippets
  # GET /snippets.json
  def index
    if current_user
      @personal_snippets = current_user.snippets.order(is_featured: :desc, name: :asc).all
      @public_snippets   = Snippet.where.not(author_id: current_user.id).where(is_private: false).order(is_featured: :desc, name: :asc).all
    else
      @public_snippets   = Snippet.all
    end
  end

  # GET /snippets/1
  # GET /snippets/1.json
  def show
  end

  # GET /snippets/new
  def new
    @snippet = current_user.snippets.new
    build_from_dup
  end

  # GET /snippets/1/edit
  def edit
  end

  # POST /snippets
  # POST /snippets.json
  def create
    @snippet = current_user.snippets.new(snippet_params)

    respond_to do |format|
      if @snippet.save
        format.html { redirect_to @snippet, notice: 'Snippet was successfully created.' }
        format.json { render :show, status: :created, location: @snippet }
      else
        format.html { render :new }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /snippets/1
  # PATCH/PUT /snippets/1.json
  def update
    respond_to do |format|
      if @snippet.update(snippet_params)
        format.html { redirect_to @snippet, notice: 'Snippet was successfully updated.' }
        format.json { render :show, status: :ok, location: @snippet }
      else
        format.html { render :edit }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /snippets/1
  # DELETE /snippets/1.json
  def destroy
    @snippet.destroy
    respond_to do |format|
      format.html { redirect_to snippets_url, notice: 'Snippet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def build_from_dup
      if params[:dup]
        original_snippet      = Snippet.find(params[:dup])
        @snippet              = original_snippet.dup
        @snippet.author       = current_user
        
        @snippet.name += " Copy"
      end
    end

    def verify_privacy_settings
      unless current_user and current_user.can_edit_generator(@snippet.id)
        if @snippet.is_private
          unless params[:token] and params[:token] == @snippet.privacy_token
            redirect_to root_url, notice: "The generator you're trying to access is private."
          end
        end
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_snippet
      @snippet = Snippet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def snippet_params
      params.require(:snippet).permit(:name,
                                      :description,
                                      :install_content,
                                      :followup_content,
                                      :tags,
                                      :registration_url,
                                      :documentation_url,
                                      :is_private,
                                      :parent_id,
                                      :author_id,
                                      :is_featured)
    end
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/views/snippets/_form.html.haml
= simple_form_for(@snippet) do |f|
  = f.error_notification
  
  .form-group
    = f.input :name, input_html: { class: "form-control" }
    .privacy-option
      = f.input :is_private, label: "Private"

  - if current_user.is_admin
    .form-group
      = f.input :is_featured
  
  .form-group
    = f.input :description, input_html: { class: "form-control" }

  .row
    .col-sm-4
      .form-group
        = f.input :registration_url, input_html: { class: "form-control" }
    .col-sm-4
      .form-group
        = f.input :documentation_url, input_html: { class: "form-control" }
    .col-sm-4
      .form-group
        = f.association :parent, input_html: { class: "form-control" }
  
  .form-group
    = f.input :install_content, input_html: { class: "form-control texteditor" }
  
  .form-group
    = f.input :followup_content, input_html: { class: "form-control" }
  
  .form-group
    = f.input :tags, input_html: { class: "form-control" }

  .form-actions.text-center
    = f.button :submit, class: "btn btn-primary btn-lg"

:javascript
  $(".texteditor").each(function(){
    CodeMirror.fromTextArea($(this)[0], {
      lineWrapping: true
    });
  });


// lineWrapping: true

app/views/snippets/_snippet.html.haml
= "# Start #{snippet.name} Install"
\
= snippet.install_content
\
= "# End #{snippet.name}"

app/views/snippets/_snippet.rb.haml
= "# Start #{snippet.name} Install"
\
= snippet.install_content.html_safe
\

- if snippet.followup_content.present?
  - unless snippet.followup_content == ""
    puts "******************************************************************************"
    puts ""
    puts "Additional Instructions:"
    puts "#{snippet.followup_content}"
    puts ""
    puts "******************************************************************************"

= "# End #{snippet.name}"
= "####################################################"

app/views/snippets/_table.html.haml
%table.table
  %thead
    %tr
      %th{ colspan: 3 }
        Name
  %tbody
    - if snippets.present?
      - snippets.each do |snippet|
        %tr
          %td
            = link_to snippet.name, snippet
            - if snippet.is_featured
              %sup.text-yellow
                .fa.fa-star

          %td.small.text-muted
            = snippet.tags.split(",").map {|t| t }.join(" • ")
          %td.text-right.action-column
            = link_to new_snippet_path(dup: snippet.id), class: "btn text-muted btn-sm" do
              .fa.fa-copy
              clone
            = link_to snippet_url(snippet), class: "btn text-muted btn-sm" do
              show
            - if current_user && current_user.can_edit_snippet(snippet)
              = link_to edit_snippet_url(snippet), class: "btn text-muted btn-sm" do
                .fa.fa-pencil
                edit
    - else
      %tr
        %td.text-center{ colspan: 3 }
          %em
            = nil_notice

app/views/snippets/edit.html.haml
.container
  %h1 Editing snippet

  = render 'form'

app/views/snippets/index.html.haml
%header
  .container
    %h1
      Snippets
    %p.text-muted
      Code Snippets can be used as part of an App Template or independently for existing Rails projects.

.container
  / Nav tabs
  .pull-right
    = link_to 'New Snippet', new_snippet_path, class: "btn btn-primary btn-sm"

  %ul.nav.nav-tabs
    - if current_user
      %li.active
        %a{"aria-controls" => "personal", "data-toggle" => "tab", :href => "#personal", :role => "tab"} My Snippets
    %li
      %a{"aria-controls" => "all", "data-toggle" => "tab", :href => "#all", :role => "tab"} Public Snippets

  / Tab panes
  .tab-content.content-wrapper
    - if current_user
      #personal.tab-pane.active{:role => "tabpanel"}
        = render "table", snippets: @personal_snippets, nil_notice: "You haven't created any Snippets", anchor: "personal"

    #all.tab-pane{:role => "tabpanel"}
      = render "table", snippets: @public_snippets, nil_notice: "There are currently no Public Snippets", anchor: "all"

    %tfoot
      %tr
        %td{ colspan: 3 }

app/views/snippets/new.html.haml
.container
  %h1 New Snippet

  = render 'form'

app/views/snippets/show.html.haml
.container
  = render "shared/page_title", title: "#{@snippet.name} Snippet", author: @snippet.author.email

  - if current_user and current_user.can_edit_snippet(@snippet.id)
    .pull-right
      = link_to 'Edit Snippet', edit_snippet_path(@snippet), class: "btn btn-primary btn-sm"

  %ul.nav.nav-tabs
    %li.active
      %a{"aria-controls" => "install", "data-toggle" => "tab", :href => "#install", :role => "tab"}
        .fa.fa-terminal
        Install
    %li
      %a{"aria-controls" => "source", "data-toggle" => "tab", :href => "#source", :role => "tab"}
        .fa.fa-code
        Source

  / Tab panes
  .tab-content.content-wrapper
    #install.tab-pane.fade.in.active{:role => "tabpanel"}
      %p
        To install #{@snippet.name} within an existing rails project, run the following script:
      %pre
        rake rails:template LOCATION=
        = snippet_url(@snippet, format: :rb)

      - if @snippet.followup_content.present?
        %p
          %b Followup content:
          = @snippet.followup_content

    #source.tab-pane.fade.in{:role => "tabpanel"}
      %pre= render @snippet

  .content-footer-wrapper
    %ul.list-inline
      %li
        = link_to new_snippet_path(dup: @snippet.id) do
          .fa.fa-copy
          Clone
      - if @snippet.registration_url.present?
        %li.text-muted
          •
        %li= link_to "Registration", @snippet.registration_url

      - if @snippet.documentation_url.present?
        %li.text-muted
          •
        %li= link_to "Documentation", @snippet.documentation_url

      - @snippet.tags.split(",").each do |tag|
        %li.pull-right
          = link_to tag, url_for(tag: tag)
      %li.pull-right
        .fa.fa-tags.text-muted

app/views/snippets/show.rb.haml
= render @snippet