config/routes.rb
Rails.application.routes.draw do
  
  resources :generators,
            path: "templates" do
    member do
      post :sort_snippets
    end
  end
  
  resources :snippets
  
  devise_for :users, controllers: { sessions:      'users/sessions',
                                    registrations: 'users/registrations',
                                    passwords:     'users/passwords' }
  
  get 'resources' => 'pages#resources'
  get ':id'       => 'pages#profile', as: :user_profile

  root "pages#home"
  

end

app/views/layouts/_alerts.html.haml
- if notice
  .alert.alert-success
    = notice
- if alert
  .alert.alert-danger
    = alert

app/views/layouts/_footer.html.haml
%footer#footer.footer
  .superfooter
    .container

  .subfooter
    .container
      .row
        .col-sm-6
          %ul.list-inline
            -# %li
            -#   = link_to "View on Product Hunt", "https://www.producthunt.com/tech/product-hunt-analytics", class: "text-white", target: "_blank"
            -# %li • 
            %li
              = link_to "Send Feedback", "https://twitter.com/MorganJLopes", class: "text-white", target: "_blank"
        .col-sm-6.text-right
          %ul.list-unstyled
            %li
              Made with
              .fa.fa-heart.text-danger
              in Atlanta

app/views/layouts/_navigation.html.haml
%nav.navbar
  .container
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to root_url, class: "navbar-brand" do
        = image_tag "logo.png"
        
      .navbar-text
        %em
          Move faster on Rails
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              .fa.fa-plus
              .fa.fa-caret-down
            %ul.dropdown-menu
              %li
                = link_to 'New Template', new_generator_path
              %li
                = link_to 'New Snippet', new_snippet_path
          %li.navbar-avatar.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              = image_tag current_user.photo_url(30)
            %ul.dropdown-menu
              %li
                = link_to generators_path do
                  Templates
                  %br
                  %em.small
                    for new projects
              %li
                = link_to snippets_path do
                  Snippets
                  %br
                  %em.small
                    for existing projects
              %li.divider{:role => "separator"}
              %li
                = link_to edit_user_registration_path do
                  Settings
              %li
                = link_to "Logout", destroy_user_session_path, method: :delete
        - else
          %li
            = link_to "Sign up", new_user_registration_path
          %li
            = link_to "Login", new_user_session_path
    / /.navbar-collapse
  / /.container-fluid

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %meta{:charset => "utf-8"}
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    %meta{:content => "ie=edge", "http-equiv" => "x-ua-compatible"}
    
    %title PumpTrolley
    
    = display_meta_tags :og => {:site => @meta_site_name, :title => "#{@meta_title} | #{@meta_subtitle}", :description => @meta_description, :keywords => @meta_keywords, :type => @meta_type, :url => request.original_url, :prev => "#{request.referer}", image: @meta_image}

    %link{:href => "//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css", :rel => "stylesheet"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

    = csrf_meta_tags
    
  %body{ class: @body_class }
    = render 'layouts/alerts'
    = render 'layouts/navigation'

    #main_content
      = yield
    
    = render 'shared/integrations/ga'

    = render 'layouts/footer'

    